#!/bin/sh

free | awk '/^Mem/{
    used  = int($3)
    avail = int($2)
    usage = int((used/avail)*100)

    if (usage > 85)
        printf "^c#f7768e^"
    else if (usage > 75)
        printf "^c#e0af68^"

    print " " usage "%^d^"
}'
